"""add trip preferences and traveler type

Revision ID: 252460a7d91d
Revises: 5c068f0389c1
Create Date: 2026-09-06 10:34:32.370602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '252460a7d91d'
down_revision: Union[str, Sequence[str], None] = '5c068f0389c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_preferences',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('budget_range', sa.String(length=20), nullable=False),
    sa.Column('travel_style', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('climate_preference', sa.String(length=20), nullable=False),
    sa.Column('accommodation_pref', sa.String(length=20), nullable=False),
    sa.Column('transport_pref', sa.String(length=20), nullable=False),
    sa.Column('food_pref', sa.String(length=20), nullable=False),
    sa.Column('travel_priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_trip_preference')
    )
    op.create_index(op.f('ix_trip_preferences_trip_id'), 'trip_preferences', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_preferences_user_id'), 'trip_preferences', ['user_id'], unique=False)
    op.add_column('trips', sa.Column('traveler_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'traveler_type')
    op.drop_index(op.f('ix_trip_preferences_user_id'), table_name='trip_preferences')
    op.drop_index(op.f('ix_trip_preferences_trip_id'), table_name='trip_preferences')
    op.drop_table('trip_preferences')
    # ### end Alembic commands ###
